version: "3.8"

services:
  postgres:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    container_name: carpoolutec-postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: carpoolutec
      POSTGRES_PASSWORD: carpoolutec_secret
      POSTGRES_DB: carpoolutec_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: carpoolutec-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
